/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_recursivepenguin_webcec_cec_CECAdapter */

#ifndef _Included_com_recursivepenguin_webcec_cec_CECAdapter
#define _Included_com_recursivepenguin_webcec_cec_CECAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_recursivepenguin_webcec_cec_CECAdapter
 * Method:    getCommPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_recursivepenguin_webcec_cec_CECAdapter_getCommPath
  (JNIEnv *, jobject);

/*
 * Class:     com_recursivepenguin_webcec_cec_CECAdapter
 * Method:    getCommName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_recursivepenguin_webcec_cec_CECAdapter_getCommName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
