/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_recursivepenguin_webcec_cec_LibCEC */

#ifndef _Included_com_recursivepenguin_webcec_cec_LibCEC
#define _Included_com_recursivepenguin_webcec_cec_LibCEC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_recursivepenguin_webcec_cec_LibCEC
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_recursivepenguin_webcec_cec_LibCEC_setup
  (JNIEnv *, jobject);

/*
 * Class:     com_recursivepenguin_webcec_cec_LibCEC
 * Method:    audioMute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_recursivepenguin_webcec_cec_LibCEC_audioMute
  (JNIEnv *, jobject);

/*
 * Class:     com_recursivepenguin_webcec_cec_LibCEC
 * Method:    audioUnMute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_recursivepenguin_webcec_cec_LibCEC_audioUnMute
  (JNIEnv *, jobject);

/*
 * Class:     com_recursivepenguin_webcec_cec_LibCEC
 * Method:    detectAdaptersNative
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_com_recursivepenguin_webcec_cec_LibCEC_detectAdaptersNative
  (JNIEnv *, jobject);

/*
 * Class:     com_recursivepenguin_webcec_cec_LibCEC
 * Method:    open
 * Signature: (Lcom/recursivepenguin/webcec/cec/CECAdapter;)V
 */
JNIEXPORT void JNICALL Java_com_recursivepenguin_webcec_cec_LibCEC_open
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_recursivepenguin_webcec_cec_LibCEC
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_recursivepenguin_webcec_cec_LibCEC_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
